export default {
  login: "raihan705",
  id: 12727580,
  node_id: "MDQ6VXNlcjEyNzI3NTgw",
  avatar_url: "https://avatars.githubusercontent.com/u/12727580?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/raihan705",
  html_url: "https://github.com/raihan705",
  followers_url: "https://api.github.com/users/raihan705/followers",
  following_url:
    "https://api.github.com/users/raihan705/following{/other_user}",
  gists_url: "https://api.github.com/users/raihan705/gists{/gist_id}",
  starred_url: "https://api.github.com/users/raihan705/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/raihan705/subscriptions",
  organizations_url: "https://api.github.com/users/raihan705/orgs",
  repos_url: "https://api.github.com/users/raihan705/repos",
  events_url: "https://api.github.com/users/raihan705/events{/privacy}",
  received_events_url: "https://api.github.com/users/raihan705/received_events",
  type: "User",
  site_admin: false,
  name: "Raihan Uddin",
  company: null,
  blog: "",
  location: "Finland",
  email: null,
  hireable: null,
  bio: "I am a Javascript developer working with React, Redux, Next, and Typescript. I enjoy learning new technologies.",
  twitter_username: null,
  public_repos: 9,
  public_gists: 0,
  followers: 0,
  following: 0,
  created_at: "2015-06-03T07:58:12Z",
  updated_at: "2022-09-29T10:11:59Z",
};
